# SIte settings
# theme: jekyll-theme-cayman
title: Luoyx Blog
description: "Explain Like I'm Five | Don't Panic!"
baseurl: ""
url: "https://artificialnotimbecile.github.io"
github_username:  artificialnotimbecile

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge