# SIte settings
title: Happy Go Lucky
description: "Explain Like I'm Five"
baseurl: ""
url: "https://artificialnotimbecile.github.io"
github_username:  artificialnotimbecile

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge